Audio:

Character:
  Animation:
      format: "{asset_name}_{action}"
      export_hooks: "default"
  Mesh:
      format: "{asset_name}"
      export_hooks: "default"
  Rig:
      format: "{asset_name}_rig"
      export_hooks: "export_hooks/export_{step}.py"
  Textures:
      format: "{asset_name}_{action}"
      export_hooks: "default"
  
Concept:

Environment:

Export:

FX:

Graphic:

Mat:
