Audio:

Character:
  - Animation:
      format: "{asset_name}_{action}"
      exprot_hooks: ""
  - Mesh:
      format: "{asset_name}"
      exprot_hooks: ""
  - Rig:
      format: "{asset_name}_rig"
      exprot_hooks: ""
  - Textures:
      format: "{asset_name}_{action}"
      exprot_hooks: ""
  
Concept:

Environment:

Export:

FX:

Graphic:

Mat:
